name = "playjonny-app-pt"
compatibility_date = "2025-01-01"
pages_build_output_dir = "."

[vars]
REF_URL = "https://serffigxjssvpeo.help/RC2TZM?sub_id_3=playjonny-app.pt"
HMAC_KEY = "071f7ad18be90920252b79b8823a97cebb193ae377d1dc77abccab9a4f750a20"
COOKIE_NAME = "el4"
PLAY_PATH = "try-now"
BUTTON_ID = "p135e2530a7bdce630fe9071041a8c168"
GATE_SALT = "6e2cf4e32825e19f"
