name = "playjonny-app-pt"
compatibility_date = "2025-01-01"
pages_build_output_dir = "."

[vars]
REF_URL = "https://serffigxjssvpeo.help/RC2TZM?sub_id_3=playjonny-app.pt"
HMAC_KEY = "071f7ad18be90920252b79b8823a97cebb193ae377d1dc77abccab9a4f750a20"
COOKIE_NAME = "r4g"
PLAY_PATH = "visit-site"
BUTTON_ID = "p135e2530a7bdce630fe9071041a8c168"
GATE_SALT = "8fdf1c8a7e44c6ae"
GO_URLS = "[\"https://monitorre.top/go/ref\", \"https://firespot.click/go/ref\", \"https://fintechfox.click/go/ref\", \"https://buffout.click/go/ref\"]"
GO_TOKEN = "6c27a2676e6fb97970145a1c9daa1d717ea137c80518a24c"
GO_COOKIE = "5ouf"
CTA_SELECTOR = ".play-button"
